"""
Project Euler Problem 44
========================

Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The first
ten pentagonal numbers are:

               1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
the value of D?
"""
import math

pentagonal_numbers = [int(n*(3*n-1) / 2) for n in range(1, 10000)]

# checks if given integer x is a pentagonal number
def is_pentagonal(x):
    n = (1 + math.sqrt(24 * x + 1)) / 6
    if n == math.floor(n):
        return True
    return False

# @TODO: make this more efficient
solutions = []
for j in range(1,len(pentagonal_numbers)-1):
    for k in range(j, len(pentagonal_numbers)-1):
        if is_pentagonal(pentagonal_numbers[j] + pentagonal_numbers[k]):
            if is_pentagonal(pentagonal_numbers[k] - pentagonal_numbers[j]):
                solutions.append(pentagonal_numbers[k] - pentagonal_numbers[j])

def euler_problem_44():
    print(min(solutions))

if __name__ == "__main__":
    euler_problem_44()