"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""
import time
import math
try:
    from helpers import find_divisors  # pylint: disable=E0611
except ModuleNotFoundError:
    from local_helpers import find_divisors


def triangle_num_n(n):
    """Given int n, returns the nth triangle number"""
    return int(n * (n+1) * 0.5)


def find_factors(x):
    result = [1]
    for i in range(2, int(math.sqrt(x))+1):
        if x % i == 0:
            result.append(i)
    return result


def solve(num_divisors=500):
    array_len = 10000
    tri_numbers = [triangle_num_n(x) for x in range(2*num_divisors*num_divisors, array_len)]
    print(len(tri_numbers))
    for t in tri_numbers:
        factors = len(find_divisors(t))
        if factors > 500:
            return t

    num_factors = 1
    x = 1
    while num_factors < 250:
        x += 1
        num_factors = len(find_factors(triangle_num_n(x)))
    print(x)
    return triangle_num_n(x)

def solve_2(num_divisors=500):
    t = 6
    d = 4
    num_divisors = len(find_divisors(t))
    while num_divisors < 500:
        num_divisors = len(find_divisors(t))
        t, d = t+d, d+1
    return t

# simple upper bound for number of divisors a number can have: 2rootn
if __name__ == "__main__":
    start_time = time.perf_counter()
    print(solve())
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(elapsed_time)

    start_time = time.perf_counter()
    print(solve_2())
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    print(elapsed_time)




