"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""
import time
import math
try:
    from helpers import find_divisors  # pylint: disable=E0611
except ModuleNotFoundError:
    from local_helpers import find_divisors


def triangle_num_n(n):
    """Given int n, returns the nth triangle number"""
    return int(n * (n+1) * 0.5)


def find_factors(x):
    result = [1]
    for i in range(2, int(math.sqrt(x))+1):
        if x % i == 0:
            result.append(i)
    return result


def solve(num_divisors=500):
    """
    solve more efficiently using the fact that triangle number n has 2 coprime factors:
    n+1 and n/2 if n is even, n and (n+1)/2 if n is odd
    """
    n = 3
    factors = 2
    next_factor_divisors = 1
    while factors < num_divisors:
        factors = next_factor_divisors
        if n % 2 == 0:
            next_factor = n+1
        else:
            next_factor = int((n+1) / 2)
        next_factor_divisors = len(find_divisors(next_factor))
        factors = factors * next_factor_divisors
        n += 1
    return triangle_num_n(n-1)


if __name__ == "__main__":
    start_time = time.perf_counter()
    print(solve())
    end_time = time.perf_counter()
    elapsed_time = end_time - start_time
    # print(elapsed_time)
