"""
Project Euler Problem 44
========================

Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The first
ten pentagonal numbers are:

               1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
the value of D?
"""
import math


def solve():
    """ Solve problem 44 """
    pentagonal_numbers = [int(n * (3 * n - 1) / 2) for n in range(1, 6000)]
    pentagonal_number_set = set(pentagonal_numbers)

    solutions = []
    for j in range(1, len(pentagonal_numbers) - 1):
        for k in range(j, len(pentagonal_numbers) - 1):
            if pentagonal_numbers[j] + pentagonal_numbers[k] in pentagonal_number_set:
                if pentagonal_numbers[k] - pentagonal_numbers[j] in pentagonal_number_set:
                    solutions.append(
                        pentagonal_numbers[k] - pentagonal_numbers[j])

    return min(solutions)


if __name__ == "__main__":
    print(solve())
