"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""
import math


def triangle_num_n(n):
    """Given int n, returns the nth triangle number"""
    return int(n * (n+1) * 0.5)


def find_factors(x):
    result = [1]
    for i in range(2, int(math.sqrt(x))+1):
        if x % i == 0:
            result.append(i)
    return result


def euler_problem_12():
    num_factors = 1
    x = 1
    while num_factors < 250:
        x += 1
        num_factors = len(find_factors(triangle_num_n(x)))
    print(triangle_num_n(x))


if __name__ == "__main__":
    euler_problem_12()
