"""
Project Euler Problem 101
=========================

If we are presented with the first k terms of a sequence it is impossible
to say with certainty the value of the next term, as there are infinitely
many polynomial functions that can model the sequence.

As an example, let us consider the sequence of cube numbers. This is
defined by the generating function, u[n] = n^3: 1, 8, 27, 64, 125, 216,
...

Suppose we were only given the first two terms of this sequence. Working
on the principle that "simple is best" we should assume a linear
relationship and predict the next term to be 15 (common difference 7).
Even if we were presented with the first three terms, by the same
principle of simplicity, a quadratic relationship should be assumed.

We shall define OP(k, n) to be the nth term of the optimum polynomial
generating function for the first k terms of a sequence. It should be
clear that OP(k, n) will accurately generate the terms of the sequence for
n <= k, and potentially the first incorrect term (FIT) will be OP(k, k+1); in
which case we shall call it a bad OP (BOP).

As a basis, if we were only given the first term of sequence, it would be
most sensible to assume constancy; that is, for n >= 2, OP(1, n) = u[1].

Hence we obtain the following OPs for the cubic sequence:

OP(1, n) = 1               1, 1, 1, 1, ...
OP(2, n) = 7n - 6          1, 8, 15, ...
OP(3, n) = 6n^2 - 11n + 6  1, 8, 27, 58, ...
OP(4, n) = n^3             1, 8, 27, 64, 125, ...

Clearly no BOPs exist for k >= 4.

By considering the sum of FITs generated by the BOPs (indicated in red
above), we obtain 1 + 15 + 58 = 74.

Consider the following tenth degree polynomial generating function:

        u[n] = 1 - n + n^2 n^3 + n^4 n^5 + n^6 n^7 + n^8 n^9 + n^10

Find the sum of FITs for the BOPs.
"""
import math
# first 15 terms: 1, 1, 683, 44287, 838861, 8138021, 51828151, 247165843, 954437177, 3138105961, 9090909091, 23775972551, 57154490053, 128011456717, 269971011311

def u(n):
    return 1 - n + n**2 - n**3 + n**4 - n**5 + n**6 - n**7 + n**8 - n**9 + n**10

u_vals = [u(x) for x in range(15)]

def find_fit(op):
    n = 1
    while op(n) == u(n):
        n += 1
    return op(n)

def find_op_k(k):
    def op_k(n):
        total = 0
        for i in range(1, k+1):
            lagrange_prod = 1
            for j in range(1, k+1):
                if i==j:
                    continue
                lagrange_prod *= (n - j) / (i - j)
            total += u_vals[i] * lagrange_prod
        return total
    return op_k

fit_sum = 0
for i in range(1, 11):
    func = find_op_k(i)
    fit_sum += find_fit(func)
print(int(fit_sum))